version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: fastapi_web
    environment:
      - DATABASE_URL=mysql+mysqlconnector://user:password@db/mydatabase
      - OTHER_ENV_VARIABLES=values
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql_data:
