version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: fastapi_web
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db/mydatabase
      - OTHER_ENV_VARIABLES=values
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: