version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: fastapi_web
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OTHER_ENV_VARIABLES: ${OTHER_ENV_VARIABLES}
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql_data:
