version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_web
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OTHER_ENV_VARIABLES: ${OTHER_ENV_VARIABLES}
      MYSQL_HOST: db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

    
  db:
    image: mysql:8
    container_name: mysql_db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-init.d/init.sql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
